### ISSUE TITLE
Empty space in server folders

### ISSUE THREAD

**Issue by Guest257351** [Xhylo/Visual-Studio-Code-BD-theme#20]
When servers are put together in a folder there is empty space at the bottom of the folder. This space is bigger if there are more servers in the folder.

I assume this is because the space allocated for each server is bigger than the actual space it takes up.

**Comment by Guest257351** [comment]
![image](https://user-images.githubusercontent.com/57662212/152075019-bdccfe49-4675-4db9-ba47-2531b6d12048.png) ![image](https://user-images.githubusercontent.com/57662212/152075058-b2bcf609-1d9f-42f0-a2bc-e23ca78cda98.png)

**Comment by PapaSmurf-ML64** [comment]
I've poked around in this as it was bothering me as well, it seems the problem lies in 
```CSS
div[id*="folder-items"] {
	height: auto !important;
}
```
This item is now a `ul` instead of a `div`. @Guest257351 adding 
```CSS
ul[id*="folder-items"] {
	height: auto !important;
}
``` 
into your Custom CSS will temporarily fix the issue until it can be properly fixed.
